---
title: '20190917'
author: "Jared Garfinkel"
date: "9/17/2019"
output: html_document
---

## Data Wrangling I

```{r load library}
library(tidyverse)
```

## Load in a dataset

```{r read in a dataset}
## reads in a dataset
litters_data = read_csv(file = "./data_import_examples/data_import_examples/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

fas_pups = read_csv(file = "./data_import_examples/data_import_examples/FAS_pups.csv")
fas_pups = janitor::clean_names(fas_pups)
```

## Selecting

```{r manipulation}
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight)

select(litters_data, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, everything())

select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_born_alive)

select(litters_data, GROUP = group, litter_number)

rename(litters_data, Group = group)

```

## Filtering!

```{r filtering}
filter(litters_data, group == "Con7")

filter(litters_data, gd_of_birth == 20)

filter(litters_data, gd_of_birth >= 20)

filter(litters_data, pups_born_alive < 6)

filter(litters_data, pups_born_alive < 6, group == "Con7")

filter(litters_data, gd_of_birth == !19)

filter(litters_data, group == "Con7" | group == "Mod8")

filter(litters_data, group %in% c("Con7", "Mod8"))

filter(litters_data, pups_born_alive >= 4, pups_born_alive <= 6)

filter(litters_data, gd0_weight + gd18_weight < 70)

## Don't do this
#
# filter(litters_data, !is.na(gd0_weight))
#
# Use this instead

drop_na(litters_data)

drop_na(litters_data, gd0_weight)

# group %in% c("Con7", "Con8")
# group == "Con7" & gd_of_birth == 20 
```

## Mutating!!

```{r mutating}
mutate(
  litters_data, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))
```

## Arrange

```{r}
arrange(litters_data, pups_born_alive)

arrange(litters_data, desc(pups_born_alive))

arrange(litters_data, pups_born_alive, gd0_weight)
```

## Pipes

Create a collection of commands

```{r}
litters_data =
  read_csv(file = "./data_import_examples/data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names() %>% 
  select(-pups_survive) %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)) %>% 
  drop_na(gd0_weight)
```

```{r, eval = FALSE}
litteres_data %>% view()

litters_data %>% pull(gd0_weight) %>% mean
```

```{r, eval = FALSE}
litters_data = 
  read_csv(file = "./data_import_examples/data_import_examples/FAS_litters.csv") %>% 
  janitor::clean_names(dat = .) %>% 
  select(.data = ., -pups_survive) %>% 
  lm(gd0_weight ~ gd18_weight, data = .)
```

